todo/urls.py
from django.conf.urls import url
from . import views

app_name = "todo"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^list/$', views.list, name='list'),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete'),

]

todo_app/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from todo.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="todo"),
    url(r'^todo/', include('todo.urls')),

]

todo/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        db_table = 'todo'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class TodoList(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Category, TodoList


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'name',
        ]
    widgets = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
    }


class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = [
            'title',
            'content',
            'category',
        ]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

todo/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Category, TodoList
from .forms import CategoryForm, TodoForm


def index(request):
    form = TodoForm(request.POST or None)
    categories = Category.objects.all()
    if request.method == 'POST':
        if "taskAdd" in request.POST:
            try:
                form = TodoForm(request.POST or None)
                form.save()
                return redirect("todo:index")
            except Category.DoesNotExist:
                messages.error(request, "Please fill all")
                return redirect("todo:index")

    return render(request, 'todo/index.html', {'form': form, 'categories': categories})


def create(request):
    form = CategoryForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('todo:index')

    return render(request, 'todo/create.html', {'form': form})


def edit(request, pk):
    context = {}
    try:
        data = TodoList.objects.get(id=pk)
    except TodoList.DoesNotExist:
        messages.error(request, 'Task not found')
        return redirect('todo:list')

    form = TodoForm(instance=data)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return redirect('todo:list')

    context['form'] = form
    return render(request, 'todo/create.html', context)


def list(request):
    context = {}
    data = TodoList.objects.all()
    context['data'] = data
    return render(request, 'todo/list.html', context)


def delete(request, pk):
    try:
        data = TodoList.objects.get(id=pk)
    except TodoList.DoesNotExist:
        messages.error(request, 'Task not found')
        return redirect('todo:list')
    data.delete()
    messages.success(request, 'Deleted Successfully')
    return redirect('todo:list')

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
{#    <link rel="stylesheet" href="{% static 'bower_components/css/style.css' %}">#}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block extra_stylesheets %}

    {% endblock %}
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

        </div>
    </div>
</div>


{% block content %}


{% endblock %}



<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% block extra_scripts %}

{% endblock %}
</body>
</html>

todo/templates/todo/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Category</label><br>
                    {{ form.name }}
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>

{% endblock %}

todo/templates/todo/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
        <div class="container">
                <h1>TodoApp</h1>
                <form method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <div class="form-group">
                                 <label for="description">Description</label>
                                {{ form.title }}
                            </div>
                        <option class="disabled" value="">Choose a category</option>
                            {{ form.category }}
                        </div>
                    <div class="row">
                        <a href="{% url 'todo:list' %}" class="btn btn-primary" name="taskAdd" type="submit">
                            <i class="fa fa-plus icon"></i> Add Task</a>&nbsp;
{#                        <button class="btn btn-primary" name="taskAdd" type="submit"><i class="fa fa-plus icon"></i>#}
{#                            Add task</button>&nbsp;#}
                        <a href="{% url 'todo:list' %}" class="btn btn-primary">View Task</a>
                    </div>
                </form>
            </div>
{% endblock %}

todo/templates/todo/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="mt-2">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Category</th>
                    <th scope="col">Date & Time</th>
                </tr>
                {% for li in data %}
                    <tr>
                        <td>{{ li.title }}</td>
                        <td>{{ li.category }}</td>
                        <td>{{ li.created_at }}</td>
                        <td>
                            <a href="{% url 'todo:edit' %}" class="btn btn-primary">Edit</a>
                            <a href="{% url 'todo:delete' %}" class="btn btn-primary">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </thead>
            </table>
         </div>
     </div>
{% endblock %}